package com.hwadee.phyexam.dao;

import com.hwadee.phyexam.entity.Parking;
import com.hwadee.phyexam.entity.ParkingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParkingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    long countByExample(ParkingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    int deleteByExample(ParkingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    int deleteByPrimaryKey(Integer parkingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    int insert(Parking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    int insertSelective(Parking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    List<Parking> selectByExample(ParkingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    Parking selectByPrimaryKey(Integer parkingid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") Parking record, @Param("example") ParkingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    int updateByExample(@Param("record") Parking record, @Param("example") ParkingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    int updateByPrimaryKeySelective(Parking record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parking
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    int updateByPrimaryKey(Parking record);
}