package com.hwadee.phyexam.entity;

public class Doctor {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.num
     *
     * @mbg.generated Wed Jul 05 10:23:23 CST 2017
     */
    private String num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.name
     *
     * @mbg.generated Wed Jul 05 10:23:23 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor.password
     *
     * @mbg.generated Wed Jul 05 10:23:23 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.num
     *
     * @return the value of doctor.num
     *
     * @mbg.generated Wed Jul 05 10:23:23 CST 2017
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.num
     *
     * @param num the value for doctor.num
     *
     * @mbg.generated Wed Jul 05 10:23:23 CST 2017
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.name
     *
     * @return the value of doctor.name
     *
     * @mbg.generated Wed Jul 05 10:23:23 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.name
     *
     * @param name the value for doctor.name
     *
     * @mbg.generated Wed Jul 05 10:23:23 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor.password
     *
     * @return the value of doctor.password
     *
     * @mbg.generated Wed Jul 05 10:23:23 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor.password
     *
     * @param password the value for doctor.password
     *
     * @mbg.generated Wed Jul 05 10:23:23 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }
}