package com.hwadee.phyexam.entity;

import java.util.Date;

import org.springframework.core.style.ToStringCreator;

public class Parking {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking.parkingid
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    private Integer parkingid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking.parkingaddress
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    private String parkingaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking.parkingstyleno
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    private String parkingstyleno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking.borrowdate
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    private Date borrowdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking.returndate
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    private Date returndate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parking.isborrowed
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    private Integer isborrowed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking.parkingid
     *
     * @return the value of parking.parkingid
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public Integer getParkingid() {
        return parkingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking.parkingid
     *
     * @param parkingid the value for parking.parkingid
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public void setParkingid(Integer parkingid) {
        this.parkingid = parkingid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking.parkingaddress
     *
     * @return the value of parking.parkingaddress
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public String getParkingaddress() {
        return parkingaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking.parkingaddress
     *
     * @param parkingaddress the value for parking.parkingaddress
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public void setParkingaddress(String parkingaddress) {
        this.parkingaddress = parkingaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking.parkingstyleno
     *
     * @return the value of parking.parkingstyleno
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public String getParkingstyleno() {
        return parkingstyleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking.parkingstyleno
     *
     * @param parkingstyleno the value for parking.parkingstyleno
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public void setParkingstyleno(String parkingstyleno) {
        this.parkingstyleno = parkingstyleno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking.borrowdate
     *
     * @return the value of parking.borrowdate
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public Date getBorrowdate() {
        return borrowdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking.borrowdate
     *
     * @param borrowdate the value for parking.borrowdate
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public void setBorrowdate(Date borrowdate) {
        this.borrowdate = borrowdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking.returndate
     *
     * @return the value of parking.returndate
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public Date getReturndate() {
        return returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking.returndate
     *
     * @param returndate the value for parking.returndate
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public void setReturndate(Date returndate) {
        this.returndate = returndate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parking.isborrowed
     *
     * @return the value of parking.isborrowed
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public Integer getIsborrowed() {
        return isborrowed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parking.isborrowed
     *
     * @param isborrowed the value for parking.isborrowed
     *
     * @mbg.generated Thu Mar 08 14:52:37 CST 2018
     */
    public void setIsborrowed(Integer isborrowed) {
        this.isborrowed = isborrowed;
    }
    
    public String toString()
    {
    	return parkingid.toString()+" "+ parkingaddress.toString();
    }
}